codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false

coverage:
  range: "50...80"
  status:
    project:
      default:
        target: 80%
    patch:
      default:
        target: 80%
