// Code generated by cmd/generate. DO NOT EDIT.

package timeseq

import (
	"errors"
	"sort"
	"sync"
	"time"
)

// Int16 is a time point with int16 value inside
type Int16 struct {
	Time  time.Time
	Value int16
}

// IsZero return if time and value are both zero
func (v Int16) IsZero() bool {
	return v.Value == 0 && v.Time.IsZero()
}

// Equal return if time and value are both equal
func (v Int16) Equal(n Int16) bool {
	return v.Value == n.Value && v.Time.Equal(n.Time)
}

// Int16s is a alias of Int16 slice
type Int16s []Int16

// Len implements Interface.Len()
func (s Int16s) Len() int {
	return len(s)
}

// Swap implements Interface.Swap()
func (s Int16s) Swap(i, j int) {
	s[i], s[j] = s[j], s[i]
}

// Time implements Interface.Time()
func (s Int16s) Time(i int) time.Time {
	return s[i].Time
}

// Slice implements Interface.Slice()
func (s Int16s) Slice(i, j int) Interface {
	return s[i:j]
}

// Int16Seq is a wrapper with useful methods of Int16 slice
type Int16Seq struct {
	slice Int16s

	indexOnce  sync.Once
	timeIndex  map[timeKey][]int
	valueIndex map[int16][]int
	valueSlice []int
}

// NewInt16Seq return *Int16Seq with copied slice inside
func NewInt16Seq(slice Int16s) *Int16Seq {
	temp := make(Int16s, len(slice))
	copy(temp, slice)
	return WrapInt16Seq(temp)
}

// WrapInt16Seq return *Int16Seq with origin slice inside
func WrapInt16Seq(slice Int16s) *Int16Seq {
	if !IsSorted(slice) {
		Sort(slice)
	}
	return newInt16Seq(slice)
}

func newInt16Seq(slice Int16s) *Int16Seq {
	ret := &Int16Seq{
		slice: slice,
	}
	return ret
}

func (s *Int16Seq) buildIndex() {
	s.indexOnce.Do(func() {
		timeIndex := make(map[timeKey][]int, len(s.slice))
		valueIndex := make(map[int16][]int, len(s.slice))
		valueSlice := s.valueSlice[:0]
		for i, v := range s.slice {
			k := newTimeKey(v.Time)
			timeIndex[k] = append(timeIndex[k], i)
			valueIndex[v.Value] = append(valueIndex[v.Value], i)
			valueSlice = append(valueSlice, i)
		}
		sort.SliceStable(valueSlice, func(i, j int) bool {
			return s.slice[valueSlice[i]].Value < s.slice[valueSlice[j]].Value
		})
		s.timeIndex = timeIndex
		s.valueIndex = valueIndex
		s.valueSlice = valueSlice
	})
}

func (s *Int16Seq) resetIndex() {
	s.indexOnce = sync.Once{}
}

// Int16s return a replica of inside slice
func (s *Int16Seq) Int16s() Int16s {
	slice := make(Int16s, len(s.slice))
	copy(slice, s.slice)
	return slice
}

// Len return length of inside slice
func (s *Int16Seq) Len() int {
	return len(s.slice)
}

// Index return element of inside slice, return zero if index is out of range
func (s *Int16Seq) Index(i int) Int16 {
	if i < 0 || i >= len(s.slice) {
		return Int16{}
	}
	return s.slice[i]
}

// Time return the first element with time t, return zero if not found
func (s *Int16Seq) Time(t time.Time) Int16 {
	got := s.MTime(t)
	if len(got) == 0 {
		return Int16{}
	}
	return got[0]
}

// MTime return all elements with time t, return nil if not found
func (s *Int16Seq) MTime(t time.Time) Int16s {
	s.buildIndex()
	index := s.timeIndex[newTimeKey(t)]
	if len(index) == 0 {
		return nil
	}
	ret := make(Int16s, len(index))
	for i, v := range index {
		ret[i] = s.slice[v]
	}
	return ret
}

// Value return the first element with value v, return zero if not found
func (s *Int16Seq) Value(v int16) Int16 {
	got := s.MValue(v)
	if len(got) == 0 {
		return Int16{}
	}
	return got[0]
}

// MValue return all elements with value v, return nil if not found
func (s *Int16Seq) MValue(v int16) Int16s {
	s.buildIndex()
	index := s.valueIndex[v]
	if len(index) == 0 {
		return nil
	}
	ret := make(Int16s, len(index))
	for i, v := range index {
		ret[i] = s.slice[v]
	}
	return ret
}

// Traverse call fn for every element one by one, break if fn return true
func (s *Int16Seq) Traverse(fn func(i int, v Int16) (stop bool)) {
	for i, v := range s.slice {
		if fn != nil && fn(i, v) {
			break
		}
	}
}

// Sum return sum of all values
func (s *Int16Seq) Sum() int16 {
	var ret int16
	for _, v := range s.slice {
		ret += v.Value
	}
	return ret
}

// Max return the element with max value, return zero if empty
func (s *Int16Seq) Max() Int16 {
	var max Int16
	found := false
	for _, v := range s.slice {
		if !found {
			max = v
			found = true
		} else if v.Value > max.Value {
			max = v
		}
	}
	return max
}

// Min return the element with min value, return zero if empty
func (s *Int16Seq) Min() Int16 {
	var min Int16
	found := false
	for _, v := range s.slice {
		if !found {
			min = v
			found = true
		} else if v.Value < min.Value {
			min = v
		}
	}
	return min
}

// First return the first element, return zero if empty
func (s *Int16Seq) First() Int16 {
	if len(s.slice) == 0 {
		return Int16{}
	}
	return s.slice[0]
}

// Last return the last element, return zero if empty
func (s *Int16Seq) Last() Int16 {
	if len(s.slice) == 0 {
		return Int16{}
	}
	return s.slice[len(s.slice)-1]
}

// Percentile return the element matched with percentile pct, return zero if empty,
// the pct's valid range is be [0, 1], it will be treated as 1 if greater than 1, as 0 if smaller than 0
func (s *Int16Seq) Percentile(pct float64) Int16 {
	s.buildIndex()
	if len(s.slice) == 0 {
		return Int16{}
	}
	if pct > 1 {
		pct = 1
	}
	if pct < 0 {
		pct = 0
	}
	i := int(float64(len(s.slice))*pct - 1)
	if i < 0 {
		i = 0
	}
	return s.slice[s.valueSlice[i]]
}

// Range return a sub *Int16Seq with specified interval
func (s *Int16Seq) Range(interval Interval) *Int16Seq {
	slice := Range(s.slice, interval).(Int16s)
	return newInt16Seq(slice)
}

// Merge merge slices to inside slice according to the specified rule
func (s *Int16Seq) Merge(fn func(t time.Time, v1, v2 *int16) *int16, slices ...Int16s) error {
	if fn == nil {
		return errors.New("nil fn")
	}

	if len(slices) == 0 {
		return nil
	}

	slice1 := s.slice
	for _, slice2 := range slices {
		if !IsSorted(slice2) {
			temp := make(Int16s, len(slice2))
			copy(temp, slice2)
			Sort(temp)
			slice2 = temp
		}
		var got Int16s
		for i1, i2 := 0, 0; i1 < len(slice1) || i2 < len(slice2); {
			var (
				t time.Time
				v *int16
			)
			switch {
			case i1 == len(slice1):
				t = slice2[i2].Time
				v2 := slice2[i2].Value
				v = fn(t, nil, &v2)
				i2++
			case i2 == len(slice2):
				t = slice1[i1].Time
				v1 := slice1[i1].Value
				v = fn(t, &v1, nil)
				i1++
			case slice1[i1].Time.Equal(slice2[i2].Time):
				t = slice1[i1].Time
				v1 := slice1[i1].Value
				v2 := slice2[i2].Value
				v = fn(t, &v1, &v2)
				i1++
				i2++
			case slice1[i1].Time.Before(slice2[i2].Time):
				t = slice1[i1].Time
				v1 := slice1[i1].Value
				v = fn(t, &v1, nil)
				i1++
			case slice1[i1].Time.After(slice2[i2].Time):
				t = slice2[i2].Time
				v2 := slice2[i2].Value
				v = fn(t, nil, &v2)
				i2++
			}
			if v != nil {
				got = append(got, Int16{
					Time:  t,
					Value: *v,
				})
			}
		}
		slice1 = got
	}

	s.slice = slice1
	s.resetIndex()
	return nil
}

// Aggregate aggregate inside slice according to the specified rule
func (s *Int16Seq) Aggregate(fn func(t time.Time, slice Int16s) *int16, duration time.Duration, interval Interval) error {
	if fn == nil {
		return errors.New("nil fn")
	}

	got := Int16s{}
	temp := Int16s{}

	if duration <= 0 {
		for i := 0; i < s.Len(); {
			t := s.slice[i].Time
			if !interval.Contain(t) {
				i++
				continue
			}
			temp = temp[:0]
			for i < s.slice.Len() && t.Equal(s.slice[i].Time) {
				temp = append(temp, s.slice[i])
				i++
			}
			v := fn(t, temp)
			if v != nil {
				got = append(got, Int16{
					Time:  t,
					Value: *v,
				})
			}
		}
	} else {
		var begin time.Time
		if len(s.slice) > 0 {
			begin = s.slice[0].Time.Truncate(duration)
		}
		if interval.NotBefore != nil {
			begin = (*interval.NotBefore).Truncate(duration)
			if begin.Before(*interval.NotBefore) {
				begin = begin.Add(duration)
			}
		}
		for t, i := begin, 0; i < s.Len() && interval.Contain(t); t = t.Add(duration) {
			temp = temp[:0]
			itv := BeginAt(t).EndAt(t.Add(duration))
			for i < s.slice.Len() && itv.Contain(s.slice[i].Time) {
				temp = append(temp, s.slice[i])
				i++
			}
			v := fn(t, temp)
			if v != nil {
				got = append(got, Int16{
					Time:  t,
					Value: *v,
				})
			}
		}
	}

	s.slice = got
	s.resetIndex()
	return nil
}

// Trim remove the elements which make fn return true
func (s *Int16Seq) Trim(fn func(i int, v Int16) bool) error {
	if fn == nil {
		return errors.New("nil fn")
	}

	updated := false
	slice := make(Int16s, 0)
	for i, v := range s.slice {
		if fn(i, v) {
			updated = true
		} else {
			slice = append(slice, v)
		}
	}

	if updated {
		s.slice = slice
		s.resetIndex()
	}
	return nil
}

// Clone return a new *Int16Seq with copied slice inside
func (s *Int16Seq) Clone() *Int16Seq {
	if s == nil {
		return nil
	}
	return newInt16Seq(s.slice)
}
