// Code generated by cmd/generate. DO NOT EDIT.
package timeseq

import (
	"errors"
	"sort"
	"time"
)

type String struct {
	Time  time.Time
	Value string
}

type Strings []String

func (s Strings) Len() int {
	return len(s)
}

func (s Strings) Swap(i, j int) {
	s[i], s[j] = s[j], s[i]
}

func (s Strings) Time(i int) time.Time {
	return s[i].Time
}

func (s Strings) Slice(i, j int) Slice {
	return s[i:j]
}

type StringSeq struct {
	slice      Strings
	timeIndex  map[timeKey][]int
	valueIndex map[string][]int
	valueSlice []int
}

func NewStringSeq(slice Strings) *StringSeq {
	temp := make(Strings, len(slice))
	copy(temp, slice)
	slice = temp

	Sort(slice)
	sort.SliceStable(slice, func(i, j int) bool {
		return slice[i].Time.Before(slice[j].Time)
	})
	return newStringSeq(slice)
}

func newStringSeq(slice Strings) *StringSeq {
	ret := &StringSeq{
		slice: slice,
	}
	ret.buildIndex()
	return ret
}

func (s *StringSeq) buildIndex() {
	timeIndex := make(map[timeKey][]int, len(s.slice))
	valueIndex := make(map[string][]int, len(s.slice))
	valueSlice := s.valueSlice[:0]
	for i, v := range s.slice {
		k := newTimeKey(v.Time)
		timeIndex[k] = append(timeIndex[k], i)
		valueIndex[v.Value] = append(valueIndex[v.Value], i)
		valueSlice = append(valueSlice, i)
	}
	sort.SliceStable(valueSlice, func(i, j int) bool {
		return s.slice[valueSlice[i]].Value < s.slice[valueSlice[j]].Value
	})
	s.timeIndex = timeIndex
	s.valueIndex = valueIndex
	s.valueSlice = valueSlice
}

func (s *StringSeq) Strings() Strings {
	slice := make(Strings, len(s.slice))
	copy(slice, s.slice)
	return slice
}

func (s *StringSeq) Index(i int) String {
	if i < 0 || i >= len(s.slice) {
		return String{}
	}
	return s.slice[i]
}

func (s *StringSeq) Time(t time.Time) Strings {
	index := s.timeIndex[newTimeKey(t)]
	if len(index) == 0 {
		return nil
	}
	ret := make(Strings, len(index))
	for i, v := range index {
		ret[i] = s.slice[v]
	}
	return ret
}

func (s *StringSeq) Value(v string) Strings {
	index := s.valueIndex[v]
	if len(index) == 0 {
		return nil
	}
	ret := make(Strings, len(index))
	for i, v := range index {
		ret[i] = s.slice[v]
	}
	return ret
}

func (s *StringSeq) Visit(fn func(i int, v String) (stop bool)) {
	for i, v := range s.slice {
		if fn != nil && fn(i, v) {
			break
		}
	}
}

func (s *StringSeq) Sum() string {
	var ret string
	for _, v := range s.slice {
		ret += v.Value
	}
	return ret
}

func (s *StringSeq) Count() int {
	return len(s.slice)
}

func (s *StringSeq) Max() String {
	var max String
	found := false
	for _, v := range s.slice {
		if !found {
			max = v
			found = true
		} else if v.Value < max.Value {
			max = v
		}
	}
	return max
}

func (s *StringSeq) Min() String {
	var min String
	found := false
	for _, v := range s.slice {
		if !found {
			min = v
			found = true
		} else if v.Value < min.Value {
			min = v
		}
	}
	return min
}

func (s *StringSeq) First() String {
	if len(s.slice) == 0 {
		return String{}
	}
	return s.slice[0]
}

func (s *StringSeq) Last() String {
	if len(s.slice) == 0 {
		return String{}
	}
	return s.slice[len(s.slice)-1]
}

func (s *StringSeq) Percentile(pct float64) String {
	if len(s.slice) == 0 {
		return String{}
	}
	if pct > 1 {
		pct = 1
	}
	if pct < 0 {
		pct = 0
	}
	i := int(float64(len(s.slice))*pct - 1)
	if i < 0 {
		i = 0
	}
	return s.slice[s.valueSlice[i]]
}

func (s *StringSeq) Range(interval Interval) *StringSeq {
	slice := Range(s.slice, interval).(Strings)
	return newStringSeq(slice)
}

func (s *StringSeq) Merge(fn func(t time.Time, v1, v2 *string) *string, slices ...Strings) error {
	if fn == nil {
		return errors.New("nil fn")
	}

	if len(slices) == 0 {
		return nil
	}

	slice1 := s.slice
	for _, slice2 := range slices {
		if !IsSorted(slice2) {
			temp := make(Strings, len(slice2))
			copy(temp, slice2)
			Sort(temp)
			slice2 = temp
		}
		var got Strings
		for i1, i2 := 0, 0; i1 < len(slice1) || i2 < len(slice2); {
			var (
				t time.Time
				v *string
			)
			switch {
			case i1 == len(slice1):
				t = slice2[i2].Time
				v2 := slice2[i2].Value
				v = fn(t, nil, &v2)
				i2++
			case i2 == len(slice2):
				t = slice2[i1].Time
				v1 := slice1[i1].Value
				v = fn(t, &v1, nil)
				i1++
			case slice1[i1].Time.Equal(slice2[i2].Time):
				t = slice1[i1].Time
				v1 := slice1[i1].Value
				v2 := slice2[i2].Value
				v = fn(t, &v1, &v2)
				i1++
				i2++
			case slice1[i1].Time.Before(slice2[i2].Time):
				t = slice1[i1].Time
				v1 := slice1[i1].Value
				v = fn(t, &v1, nil)
				i1++
			case slice1[i1].Time.After(slice2[i2].Time):
				t = slice1[i2].Time
				v2 := slice2[i2].Value
				v = fn(t, nil, &v2)
				i2++
			}
			if v != nil {
				got = append(got, String{
					Time:  t,
					Value: *v,
				})
			}
		}
		slice1 = got
	}

	s.slice = slice1
	s.buildIndex()
	return nil
}

func (s *StringSeq) Aggregate(fn func(t time.Time, slice Strings) *string, duration time.Duration, begin, end *time.Time) error {
	if fn == nil {
		return errors.New("nil fn")
	}

	if duration <= 0 {
		return errors.New("invalid duration")
	}

	var bg, ed time.Time
	if len(s.slice) > 0 {
		bg = s.slice[0].Time.Truncate(duration)
		ed = s.slice[len(s.slice)-1].Time
	}
	if begin != nil {
		bg = (*begin).Truncate(duration)
	}
	if end != nil {
		ed = *end
	}

	got := Strings{}
	slice := Strings{}
	i := 0
	for t := bg; t.Before(ed); t = t.Add(duration) {
		slice = slice[:0]
		for i < s.slice.Len() &&
			!s.slice[i].Time.After(t) &&
			s.slice[i].Time.Before(t.Add(duration)) {
			slice = append(slice, s.slice[i])
			i++
		}
		v := fn(t, slice)
		if v != nil {
			got = append(got, String{
				Time:  t,
				Value: *v,
			})
		}
	}

	s.slice = got
	s.buildIndex()
	return nil
}

func (s *StringSeq) Trim(fn func(i int, v String) bool) error {
	if fn == nil {
		return errors.New("nil fn")
	}

	updated := false
	slice := s.slice[:0]
	for i, v := range s.slice {
		if fn(i, v) {
			updated = true
		} else {
			slice = append(slice, v)
		}
	}

	if !updated {
		s.slice = slice
		s.buildIndex()
	}
	return nil
}
