// Code generated by cmd/generate. DO NOT EDIT.

// Code generated by cmd/generate. DO NOT EDIT.

package timeseq

import (
	"sort"
	"sync"
	"time"
)

// Float64 is a time point with float64 value inside
type Float64 struct {
	Time  time.Time
	Value float64
}

// IsZero returns if time and value are both zero
func (v Float64) IsZero() bool {
	return v.Value == 0 && v.Time.IsZero()
}

// Equal returns if time and value are both equal
func (v Float64) Equal(n Float64) bool {
	return v.Value == n.Value && v.Time.Equal(n.Time)
}

// Float64s is a alias of Float64 slice
type Float64s []Float64

// Len implements Interface.Len()
func (s Float64s) Len() int {
	return len(s)
}

// Swap implements Interface.Swap()
func (s Float64s) Swap(i, j int) {
	s[i], s[j] = s[j], s[i]
}

// Time implements Interface.Time()
func (s Float64s) Time(i int) time.Time {
	return s[i].Time
}

// Slice implements Interface.Slice()
func (s Float64s) Slice(i, j int) Interface {
	return s[i:j]
}

// Float64Seq is a wrapper with useful methods of Float64 slice
type Float64Seq struct {
	innerSlice Float64s

	indexOnce  sync.Once
	timeIndex  map[timeKey][]int
	valueIndex map[float64][]int
	valueSlice []int
}

// NewFloat64Seq returns *Float64Seq with copied slice inside
func NewFloat64Seq(slice Float64s) *Float64Seq {
	temp := make(Float64s, len(slice))
	copy(temp, slice)
	return WrapFloat64Seq(temp)
}

// WrapFloat64Seq returns *Float64Seq with origin slice inside
func WrapFloat64Seq(slice Float64s) *Float64Seq {
	if !IsSorted(slice) {
		Sort(slice)
	}
	return newFloat64Seq(slice)
}

func newFloat64Seq(slice Float64s) *Float64Seq {
	ret := &Float64Seq{
		innerSlice: slice,
	}
	return ret
}

func (s *Float64Seq) slice() Float64s {
	if s == nil {
		return nil
	}
	return s.innerSlice
}

func (s *Float64Seq) buildIndex() {
	if s == nil {
		return
	}
	s.indexOnce.Do(func() {
		timeIndex := make(map[timeKey][]int, len(s.innerSlice))
		valueIndex := make(map[float64][]int, len(s.innerSlice))
		valueSlice := s.valueSlice[:0]
		for i, v := range s.innerSlice {
			k := newTimeKey(v.Time)
			timeIndex[k] = append(timeIndex[k], i)
			valueIndex[v.Value] = append(valueIndex[v.Value], i)
			valueSlice = append(valueSlice, i)
		}
		sort.SliceStable(valueSlice, func(i, j int) bool {
			return s.innerSlice[valueSlice[i]].Value < s.innerSlice[valueSlice[j]].Value
		})
		s.timeIndex = timeIndex
		s.valueIndex = valueIndex
		s.valueSlice = valueSlice
	})
}

func (s *Float64Seq) resetIndex() {
	if s == nil {
		return
	}
	s.indexOnce = sync.Once{}
}

// Float64s returns a replica of inside slice
func (s *Float64Seq) Float64s() Float64s {
	sslice := s.slice()

	slice := make(Float64s, len(sslice))
	copy(slice, sslice)
	return slice
}

// Len returns length of inside slice
func (s *Float64Seq) Len() int {
	sslice := s.slice()
	return len(sslice)
}

// Index returns element of inside slice, returns zero if index is out of range
func (s *Float64Seq) Index(i int) Float64 {
	sslice := s.slice()
	if i < 0 || i >= len(sslice) {
		return Float64{}
	}
	return sslice[i]
}

// Time returns the first element with time t, returns zero if not found
func (s *Float64Seq) Time(t time.Time) Float64 {
	got := s.MTime(t)
	if len(got) == 0 {
		return Float64{}
	}
	return got[0]
}

// MTime returns all elements with time t, returns nil if not found
func (s *Float64Seq) MTime(t time.Time) Float64s {
	s.buildIndex()
	sslice := s.slice()
	index := s.timeIndex[newTimeKey(t)]
	if len(index) == 0 {
		return nil
	}
	ret := make(Float64s, len(index))
	for i, v := range index {
		ret[i] = sslice[v]
	}
	return ret
}

// Value returns the first element with value v, returns zero if not found
func (s *Float64Seq) Value(v float64) Float64 {
	got := s.MValue(v)
	if len(got) == 0 {
		return Float64{}
	}
	return got[0]
}

// MValue returns all elements with value v, returns nil if not found
func (s *Float64Seq) MValue(v float64) Float64s {
	s.buildIndex()
	sslice := s.slice()
	index := s.valueIndex[v]
	if len(index) == 0 {
		return nil
	}
	ret := make(Float64s, len(index))
	for i, v := range index {
		ret[i] = sslice[v]
	}
	return ret
}

// Traverse call fn for every element one by one, break if fn returns true
func (s *Float64Seq) Traverse(fn func(i int, v Float64) (stop bool)) {
	sslice := s.slice()
	for i, v := range sslice {
		if fn != nil && fn(i, v) {
			break
		}
	}
}

// Sum returns sum of all values
func (s *Float64Seq) Sum() float64 {
	var ret float64
	sslice := s.slice()
	for _, v := range sslice {
		ret += v.Value
	}
	return ret
}

// Max returns the element with max value, returns zero if empty
func (s *Float64Seq) Max() Float64 {
	var max Float64
	found := false
	sslice := s.slice()
	for _, v := range sslice {
		if !found {
			max = v
			found = true
		} else if v.Value > max.Value {
			max = v
		}
	}
	return max
}

// Min returns the element with min value, returns zero if empty
func (s *Float64Seq) Min() Float64 {
	var min Float64
	found := false
	sslice := s.slice()
	for _, v := range sslice {
		if !found {
			min = v
			found = true
		} else if v.Value < min.Value {
			min = v
		}
	}
	return min
}

// First returns the first element, returns zero if empty
func (s *Float64Seq) First() Float64 {
	sslice := s.slice()
	if len(sslice) == 0 {
		return Float64{}
	}
	return sslice[0]
}

// Last returns the last element, returns zero if empty
func (s *Float64Seq) Last() Float64 {
	sslice := s.slice()
	if len(sslice) == 0 {
		return Float64{}
	}
	return sslice[len(sslice)-1]
}

// Percentile returns the element matched with percentile pct, returns zero if empty,
// the pct's valid range is be [0, 1], it will be treated as 1 if greater than 1, as 0 if smaller than 0
func (s *Float64Seq) Percentile(pct float64) Float64 {
	s.buildIndex()
	sslice := s.slice()
	if len(sslice) == 0 {
		return Float64{}
	}
	if pct > 1 {
		pct = 1
	}
	if pct < 0 {
		pct = 0
	}
	i := int(float64(len(sslice))*pct - 1)
	if i < 0 {
		i = 0
	}
	return sslice[s.valueSlice[i]]
}

// Range returns a sub *Float64Seq with specified interval
func (s *Float64Seq) Range(interval Interval) *Float64Seq {
	sslice := s.slice()
	slice := Range(sslice, interval).(Float64s)
	return newFloat64Seq(slice)
}

// Range returns a *Float64Seq without elements which make fn returns true
func (s *Float64Seq) Trim(fn func(i int, v Float64) bool) *Float64Seq {
	sslice := s.slice()
	if fn == nil || len(sslice) == 0 {
		return s
	}

	removeM := map[int]struct{}{}
	for i, v := range sslice {
		if fn(i, v) {
			removeM[i] = struct{}{}
		}
	}
	if len(removeM) == 0 {
		return s
	}

	slice := make(Float64s, 0, len(sslice)-len(removeM))
	for i, v := range sslice {
		if _, ok := removeM[i]; ok {
			continue
		}
		slice = append(slice, v)
	}

	return newFloat64Seq(slice)
}

// Merge returns a new *Float64Seq with merged data according to the specified rule
func (s *Float64Seq) Merge(fn func(t time.Time, v1, v2 *float64) *float64, seq *Float64Seq) *Float64Seq {
	if fn == nil {
		return s
	}

	var ret Float64s

	slice1 := s.slice()
	var slice2 Float64s
	if seq != nil {
		slice2 = seq.slice()
	}

	for i1, i2 := 0, 0; i1 < len(slice1) || i2 < len(slice2); {
		var (
			t time.Time
			v *float64
		)
		switch {
		case i1 == len(slice1):
			t = slice2[i2].Time
			v2 := slice2[i2].Value
			v = fn(t, nil, &v2)
			i2++
		case i2 == len(slice2):
			t = slice1[i1].Time
			v1 := slice1[i1].Value
			v = fn(t, &v1, nil)
			i1++
		case slice1[i1].Time.Equal(slice2[i2].Time):
			t = slice1[i1].Time
			v1 := slice1[i1].Value
			v2 := slice2[i2].Value
			v = fn(t, &v1, &v2)
			i1++
			i2++
		case slice1[i1].Time.Before(slice2[i2].Time):
			t = slice1[i1].Time
			v1 := slice1[i1].Value
			v = fn(t, &v1, nil)
			i1++
		case slice1[i1].Time.After(slice2[i2].Time):
			t = slice2[i2].Time
			v2 := slice2[i2].Value
			v = fn(t, nil, &v2)
			i2++
		}
		if v != nil {
			ret = append(ret, Float64{
				Time:  t,
				Value: *v,
			})
		}
	}

	return newFloat64Seq(ret)
}

// Aggregate returns a aggregated *Float64Seq according to the specified rule
func (s *Float64Seq) Aggregate(fn func(t time.Time, slice Float64s) *float64, duration time.Duration, interval Interval) *Float64Seq {
	if fn == nil {
		return s
	}

	slice := Float64s{}
	temp := Float64s{}

	sslice := s.slice()
	if duration <= 0 {
		for i := 0; i < s.Len(); {
			t := sslice[i].Time
			if !interval.Contain(t) {
				i++
				continue
			}
			temp = temp[:0]
			for i < sslice.Len() && t.Equal(sslice[i].Time) {
				temp = append(temp, sslice[i])
				i++
			}
			v := fn(t, temp)
			if v != nil {
				slice = append(slice, Float64{
					Time:  t,
					Value: *v,
				})
			}
		}
	} else {
		var begin time.Time
		if len(sslice) > 0 {
			begin = sslice[0].Time.Truncate(duration)
		}
		if interval.NotBefore != nil {
			begin = (*interval.NotBefore).Truncate(duration)
			if begin.Before(*interval.NotBefore) {
				begin = begin.Add(duration)
			}
		}
		for t, i := begin, 0; interval.Contain(t); t = t.Add(duration) {
			temp = temp[:0]
			itv := BeginAt(t).EndAt(t.Add(duration))
			for i < len(sslice) {
				if sslice[i].Time.After(*itv.NotAfter) {
					break
				}
				if itv.Contain(sslice[i].Time) {
					temp = append(temp, sslice[i])
				}
				i++
			}
			v := fn(t, temp)
			if v != nil {
				slice = append(slice, Float64{
					Time:  t,
					Value: *v,
				})
			}
		}
	}

	return newFloat64Seq(slice)
}
